Parameters:
  myVPC:
    Type: AWS::EC2::VPC::Id
Resources: 
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId:
        Ref: myVPC
Outputs:
  InstanceSecurityGroup:
    Value: !Ref InstanceSecurityGroup
    Description: ID of security group
#    Export:
#      Name: !Sub ${AWS::StackName}-InstanceSecurityGroup